name: pase_de_lista
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.3
  csv: ^6.0.0
  shared_preferences: ^2.3.2
  path_provider: ^2.0.11
  intl: ^0.19.0
  pdf: ^3.11.1
  permission_handler: ^10.0.0
  external_path: ^1.0.2
  share_plus: ^10.1.1 

dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter_lints: ^4.0.0


flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
  uses-material-design: true


























  #


